// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bsrrccwxsfvvokcxqbpt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJzcnJjY3d4c2Z2dm9rY3hxYnB0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3Mjg4NDgsImV4cCI6MjA2MTMwNDg0OH0.w2IIHFxKHpReEL21hwtiRtwqAFAkaIzMtwUqnvlO1ew";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);